create schema api;

create table api.todos (
  id int primary key generated by default as identity,
  iscomplete boolean not null default false,
  title text not null,
  description text not null
);

insert into api.todos (title, description) values('finish tutorial 0', 'description'), ('pat self on back', 'description');

create role web_anon nologin;

grant usage on schema api to web_anon;
grant select on api.todos to web_anon;

create role authenticator noinherit login password '123456';
grant web_anon to authenticator;